version: "3.8"

services:
  agendador-tarefas:
    build: ..\Agendador-de-Tarefas
    container_name: agendador-de-tarefas
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/db_agendador
      - USUARIO_URL=http://usuario:8081
    depends_on:
      - mongo
      - usuario # Boa prática: garantir que o usuario suba antes

  bff-agendador-tarefas:
    build: .
    container_name: bff-agendador-de-tarefas
    ports:
      - "8084:8084"
    environment:
      # --- CORREÇÃO 2: Sintaxe de URL correta (http://...) ---
      - USUARIO_URL=http://usuario:8081/usuario
      - AGENDADOR_TAREFAS_URL=http://agendador-tarefas:8082/tarefas
      - NOTIFICACAO_URL=http://notificacao:8083/email

  usuario:
    build: ..\Usuario
    container_name: usuario
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_usuario
      - SPRING_DATASOURCE_USERNAME=admin123
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      - postgres

  notificacao:
    build: ..\notificacao
    container_name: notificacao
    ports:
      - "8083:8083"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: no
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_usuario

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: no
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_agendador

networks:
  default:
    driver: bridge